name: Test EC2 Connection with GHA

on:
   workflow_dispatch

jobs:
  test-ec2-connect:
    name: test ec2 connect
    runs-on: ubuntu-22.04

    steps:
      - name: setup SSH Directory 
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: make private key file 
        run: |
          echo "${{ secrets.EC2_PRIVATEKEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

      - name: test SSH connect to EC2
        env:
          HOSTNAME: ${{ secrets.EC2_HOSTNAME }}
          USER_NAME: ubuntu

        run: |
          echo "SSH 연결 테스트 시작..."

          ssh -o StrictHostKeyChecking=no \
          -o "USERKnownHostsFile=/dev/null"
          -i .\aws-ubuntu-ec2-25_5_23.pem -p 22 \
          ${USER_NAME}@${HOSTNAME} '
            echo "현재사용자: $(whoami)"
            echo "현재사용자: $(hostname)"
          '

          echo "SSH 연결 테스트 종료로..."

      - name: cleanup private key 
        if: always()
        run: |
          rm -f ~/.ssh/ec2_key